### ISSUE TITLE
tillamook county

### ISSUE THREAD

**Issue by max-mapper** [openelections/openelections-sources-or#1]
came here from https://twitter.com/openelex/status/608800130964271104

i'm from the oregon coast, and know some people in lincoln county. in addition to http://www.co.tillamook.or.us/gov/clerk/Elections%202015/2015May19ElectionResults.htm what info are you looking for, and where did you find the price?

**Comment by dwillis** [comment]
Thanks, @maxogden. We are looking for precinct-level results for primary and general elections from 2000-2014 (we can get county-wide results from the state). We emailed the county clerk, who maintains election results, and she quoted us a fee of $664. When we asked for a breakdown, this is what she emailed to us:

> The fee for each election is $3.75 locate fee and then .25 cents per page.  That is the fee if it is a 
> paper copy or if we send it in a PDF.  That is the charge that the Oregon Revised Statues say that 
> we can/or should charge.
> 
> Tassi O'Neil
> Tillamook County Clerk
> 201 Laurel Ave
> Tillamook, OR  97141
> toneil@co.tillamook.or.us
> Ph: 503-842-3402
> 1-800-488-8280 Ext. 4000
