### ISSUE TITLE
2016 Wallowa County General Election Results File

### ISSUE THREAD

**Issue by peter-redistricting-data-hub** [openelections/openelections-sources-or#12]
It seems like the 2016 Wallowa County file only contains primary results.

I've attached a 2016 General Election results file from Wallowa county, that was downloaded from here: http://records.sos.state.or.us/ORSOSWebDrawer/Record/6570960

[Wallowa.pdf](https://github.com/openelections/openelections-sources-or/files/7627359/Wallowa.pdf)

**Comment by dwillis** [comment]
@peter-redistricting-data-hub thanks!
